### ISSUE TITLE
Linter crashes when using "use-cargo"

### ISSUE THREAD

**Issue by kbjr** [oschwald/SublimeLinter-contrib-rustc#33]
If I leave `"use-cargo"` off, the linter seems to work, but adding `"use-cargo": true` causes the linter to crash. From the console:

```
SublimeLinter: #15 rust lib.rs ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in C:\Users\james\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in C:\Users\james\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 762, in lint
  File "linter in C:\Users\james\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-contrib-rustc.sublime-package", line 70, in run
AttributeError: 'module' object has no attribute 'find_file'
```

**Comment by oschwald** [comment]
I believe this is due to a breaking change in SublimeLinter 4. This could potentially be fixed with [something like this](https://github.com/oschwald/SublimeLinter-perlcritic/pull/7/commits/511b15024175bbe234f0e1ecc01d4e7c083335bf). That said, I am not sure I see the utility of this linter given that [Rust Enhanced](https://github.com/rust-lang/rust-enhanced) exists. Is there a reason to prefer this to that?

**Comment by kbjr** [comment]
I've used sublime linter for a long time, so it was just my go to choice. I'll look at Rust Enhanced and see if that will suit my needs.
