### ISSUE TITLE
Error: `'module' object has no attribute 'find_file'`

### ISSUE THREAD

**Issue by QuinnFreedman** [oschwald/SublimeLinter-contrib-rustc#34]
I'm using SublimeLinter-contrib-rustc with ST3 on Windows. Whenever I open a file with the linter enabled, i get this error:

From a little  googling it looks like maybe SublimeLinter made a breaking change and not everyone has caught up yet? I'm not sure.

```
SublimeLinter: #1 rust render.rs ERROR:
=======================================

Linter crashed.

Traceback (most recent call last):
  File "lint.backend in C:\Users\Quinn Freedman\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 100, in execute_lint_task
  File "lint.linter in C:\Users\Quinn Freedman\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter.sublime-package", line 761, in lint
  File "linter in C:\Users\Quinn Freedman\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-contrib-rustc.sublime-package", line 70, in run
AttributeError: 'module' object has no attribute 'find_file'
```

**Comment by oschwald** [comment]
This appears to be the same as #33. I am happy to accept a PR to fix it, but I think most users are better off using Rust Enhanced instead.
